### ISSUE TITLE
WTF is infinity?

### ISSUE THREAD

**Issue by milezteg** [mdamien/infinity#2]
I seriously want to know what infinity did.

**Comment by mdamien** [comment]
I updated the readme with the original article: https://archive.is/yHnUW#selection-255.0-270.0
In short, it's a trap for web crawlers.

**Comment by milezzz** [comment]
Well shit thank you, that'a actually pretty neat.  I see why it's offline.

Q:  How much of the traffic / bandwidth was from bots vs actual users?

Q:  Possible to use a dictionary file to pull the keywords from?

**Comment by milezzz** [comment]
Ahhh I see your words file now...still interested in Question 1.

**Comment by mdamien** [comment]
100% from bots :)

**Comment by milezzz** [comment]
Awww well that's a shame.  Leads me to believe the results were indexed but sandboxed by G.
